# Generated by Django 3.2 on 2024-10-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productBlenderModel', models.FileField(blank=True, null=True, upload_to='blender_models/')),
                ('colors', models.JSONField(default=list)),
                ('category', models.JSONField(default=list)),
                ('discount', models.BooleanField(default=False)),
                ('discountInPercent', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
