# Generated by Django 3.2 on 2024-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripePriceId',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
