# Generated by Django 3.2 on 2026-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stripepriceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPicture',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productBlenderModel',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
