<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 shopModel.glb -s -u --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/shopModel-transformed.glb', { useDraco: true }))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-3.89, -3.42, 1.99]} scale={1.74}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Rokkaku__Yukimi_Japanese_lantern.geometry}
        material={gltf.materials['White granite-s2']}
        position={[-0.67, 5.12, -0.21]}
        scale={0.94}
      />
    </T.Group>
    <T.Group position={[-4.74, -1.7, 1.61]} rotation={[0, 0, 1.4]} scale={2.33}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Grey_vase_1.geometry}
        material={gltf.materials['Grey-vase']}
        position={[-1.38, -0.35, 0]}
        scale={0.89}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Grey_vase_2.geometry}
        material={gltf.materials['Grey-vase']}
        position={[-1.25, -0.13, 0]}
        scale={0.89}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Grey_vase_3.geometry}
        material={gltf.materials['Grey-vase']}
        position={[-1.05, -0.28, 0]}
        scale={0.89}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Grey_vase_4.geometry}
        material={gltf.materials['Grey-vase']}
        position={[2.62, 0.48, 0]}
        scale={0.86}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Japanese_Sign_Back.geometry}
      material={gltf.materials.room_beames}
      position={[0.37, -5.87, 7.88]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={[-1.18, -4.59, -1.24]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Japanese_Sign_Back001.geometry}
      material={gltf.materials.room_beames}
      position={[0.37, -5.87, 5.92]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.39, 5.3, 1.24]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane006.geometry}
      material={gltf.nodes.Plane006.material}
      position={[-24.33, 3.75, 7.51]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={-3.16}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Japanese_Sign_Text.geometry}
      material={gltf.materials['Material.001']}
      position={[-0.32, -5.82, 7.86]}
      rotation={[0, 0, -Math.PI]}
      scale={2.19}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Low_Table.geometry}
      material={gltf.materials['Material.014']}
      position={[-4.79, 0.32, 1.56]}
      scale={[1.09, 6.19, 0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.frames_top.geometry}
      material={gltf.materials['4k-Cardboard-Old']}
      position={[-5.69, -2.78, 10.45]}
      scale={[0.11, 1.35, 1.93]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.frames_bottom.geometry}
      material={gltf.materials['4k-Cardboard-Old']}
      position={[-5.69, -2.78, 6.16]}
      scale={[0.11, 1.35, 1.93]}
    />
    <T.Group position={[-7.15, 7.54, 12.47]} rotation={[0, 0, 0.58]} scale={[0.53, 0.57, 0.44]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006.geometry}
        material={gltf.materials['Material.059']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_1.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_2.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_3.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_4.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_5.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_6.geometry}
        material={gltf.materials['Material.060']}
      />
    </T.Group>
    <T.Group position={[7.17, 7.41, 12.47]} rotation={[0, 0, -0.8]} scale={[0.53, 0.57, 0.44]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006.geometry}
        material={gltf.materials['Material.059']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_1.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_2.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_3.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_4.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_5.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006_6.geometry}
        material={gltf.materials['Material.060']}
      />
    </T.Group>
    <T.Group position={[7.92, -6.2, 14.57]} rotation={[0.25, 1.52, 1.33]} scale={[0.32, 0.21, 0.38]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder007.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cylinder007_1.geometry} material={gltf.materials.Red} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cylinder007_2.geometry} material={gltf.materials.Black} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cylinder007_3.geometry} material={gltf.materials.Lamp} />
    </T.Group>
    <T.Group position={[9.93, -6.44, 0.09]} rotation={[-0.31, 0.16, 1.1]} scale={[0.11, 0.13, 0.11]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cube022.geometry} material={gltf.materials.Material} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube022_1.geometry}
        material={gltf.materials['Material.099']}
      />
    </T.Group>
    <T.Group position={[-9.45, 5.07, 4.17]} rotation={[-Math.PI / 6, 0, 0]} scale={[1.07, 0.86, 0.04]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube018.geometry}
        material={gltf.materials['Material.017']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube018_1.geometry}
        material={gltf.materials['Material.019']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube018_2.geometry}
        material={gltf.materials['Material.017']}
      />
    </T.Group>
    <T.Group position={[-10.01, 2.97, 11.66]} rotation={[-1.85, 1.25, -1.6]} scale={[0.14, 0.15, 0.13]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009.geometry}
        material={gltf.materials['Material.051']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009_1.geometry}
        material={gltf.materials['Material.052']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009_2.geometry}
        material={gltf.materials['Material.053']}
      />
    </T.Group>
    <T.Group position={[-20.97, 2.85, 11.55]} rotation={[-2.46, -1.31, -2.38]} scale={[0.14, 0.15, 0.13]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009.geometry}
        material={gltf.materials['Material.051']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009_1.geometry}
        material={gltf.materials['Material.052']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009_2.geometry}
        material={gltf.materials['Material.053']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Circle.geometry}
      material={gltf.materials['Material.006']}
      position={[0, 0, -1.13]}
      scale={-146.05}
    />
    <T.Group position={[-7.56, -7.5, 0.11]} scale={[23.17, 21.62, 21.62]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane014_1.geometry}
        material={gltf.materials['Material.031']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane014_2.geometry}
        material={gltf.materials['Material.058']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials['Material.004']}
      position={[-17.35, -2.82, 5.23]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials['Material.011']}
      position={[-17.35, -2.82, 5.23]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials.Red}
      position={[-24.41, 3.88, 7.78]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube005.geometry}
      material={gltf.materials['Material.015']}
      position={[-27.51, -2.9, 6.33]}
      rotation={[0, 0, Math.PI / 2]}
      scale={[10.15, 6.71, 7.37]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube006.geometry}
      material={gltf.materials['Material.007']}
      position={[-17.35, -2.71, 5.23]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials.Red}
      position={[-9.44, 3.88, 7.52]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube008.geometry}
      material={gltf.materials.Red}
      position={[-17.35, -2.82, 5.23]}
      scale={[10.15, 6.71, 5.38]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials['Material.005']}
      position={[-27.95, -8.99, 13.92]}
      rotation={[-0.24, 0, 0]}
      scale={[0.35, 0.75, 0.52]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane007.geometry}
      material={gltf.materials['Material.019']}
      position={[-16.78, 4.5, 9.51]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.92, 0.67, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane017.geometry}
      material={gltf.materials['Material.019']}
      position={[-21.97, 4.5, 9.51]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.92, 0.67, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane018.geometry}
      material={gltf.materials['Material.019']}
      position={[-27.04, 4.5, 9.51]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.92, 0.67, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane011.geometry}
      material={gltf.materials['Material.019']}
      position={[-12.99, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane016.geometry}
      material={gltf.materials['Material.019']}
      position={[-18.18, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane019.geometry}
      material={gltf.materials['Material.019']}
      position={[-23.25, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane012.geometry}
      material={gltf.materials['Material.019']}
      position={[-14.17, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane015.geometry}
      material={gltf.materials['Material.019']}
      position={[-19.36, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane020.geometry}
      material={gltf.materials['Material.019']}
      position={[-24.43, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane013.geometry}
      material={gltf.materials['Material.019']}
      position={[-20.61, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane014.geometry}
      material={gltf.materials['Material.019']}
      position={[-15.42, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane021.geometry}
      material={gltf.materials['Material.019']}
      position={[-25.68, 4.51, 9.57]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[0.91, 0.61, 0.76]}
    />
    <T.Group position={[-15.68, 0.35, 15.36]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[4.69, 0.19, 2.15]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cube006_1.geometry} material={gltf.materials['2']} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006_2.geometry}
        material={gltf.materials['Material.008']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials['Material.069']}
      position={[-27.73, -2.89, 5.25]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[-5.19, -5.68, -0.09]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials['Material.069']}
      position={[-28.86, -8.15, 5.22]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={[-1, -4.88, -0.09]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials['Material.069']}
      position={[-28.86, 3.05, 5.22]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={[-1, -4.88, -0.09]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials['Material.069']}
      position={[-28.86, -0.51, 5.22]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={[-1, -4.88, -0.09]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials['Material.068']}
      position={[-28.91, -2.86, 0.26]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[-1, -5.68, -0.09]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials['Material.069']}
      position={[-28.74, -1.9, 5.1]}
      scale={0.18}
    />
    <T.Group position={[-29.2, -2.96, 8.13]} rotation={[0, 0, -1.65]} scale={[1.1, 0.77, 0.33]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010.geometry}
        material={gltf.materials['Material.070']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_1.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_2.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_3.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_4.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_5.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_6.geometry}
        material={gltf.materials['Material.060']}
      />
    </T.Group>
    <T.Group position={[-29.2, -6.67, 8.13]} rotation={[0, 0, -1.65]} scale={[1.1, 0.77, 0.33]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010.geometry}
        material={gltf.materials['Material.070']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_1.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_2.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_3.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_4.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_5.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_6.geometry}
        material={gltf.materials['Material.060']}
      />
    </T.Group>
    <T.Group position={[-29.2, 0.96, 8.13]} rotation={[0, 0, -1.65]} scale={[1.1, 0.77, 0.33]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010.geometry}
        material={gltf.materials['Material.070']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_1.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_2.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_3.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_4.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_5.geometry}
        material={gltf.materials['Material.060']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere010_6.geometry}
        material={gltf.materials['Material.060']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text001.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, 0.96, 7.66]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.34}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text002.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, 0.96, 6]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.34}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text004.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, -2.96, 6]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.34}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text005.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, -6.67, 6]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.34}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text006.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, -2.98, 7.65]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.53}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text007.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, -2.96, 2.64]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.34}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text003.geometry}
      material={gltf.materials['Material.007']}
      position={[-30.16, -2.98, 4.29]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.53}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text008.geometry}
      material={gltf.materials['Material.007']}
      position={[-29.98, -6.7, 7.65]}
      rotation={[Math.PI / 2, -1.57, 0]}
      scale={0.29}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text009.geometry}
      material={gltf.materials['Material.100']}
      position={[0.23, -5.86, 5.68]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={0.67}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text010.geometry}
      material={gltf.materials['Material.007']}
      position={[18.46, -24, -1.09]}
      rotation={[0, 0, Math.PI / 2]}
      scale={1.23}
    />
    <T.Group position={[-0.29, -12.82, 11.33]} scale={[5.33, 5.33, 11.47]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube020.geometry}
        material={gltf.materials['Material.020']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube020_1.geometry}
        material={gltf.materials['Material.102']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane008.geometry}
      material={gltf.materials['Material.029']}
      position={[5.32, -17.7, -1.19]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
      scale={[0.37, 0.77, 0.55]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane009.geometry}
      material={gltf.materials['Material.029']}
      position={[5.32, -10.49, -1.19]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
      scale={[0.37, 0.77, 0.55]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane010.geometry}
      material={gltf.materials['Material.029']}
      position={[3.93, -14.03, -0.87]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
      scale={[0.39, 0.71, 0.58]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Sphere.geometry}
      material={gltf.materials['Material.023']}
      position={[5.08, -18.03, 10.14]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.12}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Sphere003.geometry}
      material={gltf.materials['Material.023']}
      position={[5.08, -7.57, 10.14]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.12}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Sphere001.geometry}
      material={gltf.materials['Material.023']}
      position={[5.08, -18.03, 10.14]}
      scale={0.12}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Sphere002.geometry}
      material={gltf.materials['Material.023']}
      position={[5.08, -18.03, 13.97]}
      scale={0.12}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Text.geometry}
      material={gltf.materials['Material.023']}
      position={[5.16, -12.55, 11.97]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
      scale={1.95}
    />
    <T.Group position={[0.01, 0.26, 13.39]} scale={5.4}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cube029.geometry} material={gltf.materials.Red} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube029_1.geometry}
        material={gltf.materials['Material.057']}
      />
    </T.Group>
    <T.Group position={[0, 0, 6.58]} scale={-6.55}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube_1.geometry}
        material={gltf.materials.room_base_color}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube_2.geometry}
        material={gltf.materials.room_floor_color}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube_3.geometry}
        material={gltf.materials['Material.011']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.wood_beam_r.geometry}
      material={gltf.materials.room_beames}
      position={[-5.86, 6.37, 6.88]}
      rotation={[Math.PI, 0, Math.PI / 2]}
      scale={[-0.06, -0.04, -6.24]}
    />
    <T.Group position={[0.11, 0.18, 18.13]} rotation={[0, 0, -Math.PI]} scale={[0.67, 0.01, 0.67]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube005_1.geometry}
        material={gltf.materials['Material.002']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube005_2.geometry}
        material={gltf.materials['Accent.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube005_3.geometry}
        material={gltf.materials['Material.007']}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
