<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\tshirt.glb -s --transform
-->

<script lang='js'>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, interactivity, HTML } from '@threlte/extras'
  import { tweened } from 'svelte/motion'
	import { cubicOut } from 'svelte/easing'
  import { selectedProductID, selectedProductPosition, selectedProductRotation, selectedProductRotationSpeed } from '../../../stores/product_selection'
	import { cameraControls } from '../cameraControls/stores';
  import { triggerDeselect } from '../../../stores/product_selection'
  import { Audio } from '@threlte/extras'

  interactivity()

  const component = forwardEventHandlers()
  export const ref = new Group()
  export let productData
  export let startPosition = [0,3,0]
  export let startRotation = [0,0,0]

  let arrayBuffer = Uint8Array.from(atob(productData.productBlenderModel), c => c.charCodeAt(0))
  const blob = new Blob([arrayBuffer], { type: 'model/gltf-binary' });
  const glbFile = new File([blob], 'model.glb', { type: 'model/gltf-binary' });
  const url = URL.createObjectURL(glbFile);
  let gltf = useGltf(url, { useDraco: true })

  const scale = 4.5;
  const verticalProductOffset = 2.1
  let variableScale = tweened(scale, {easing: cubicOut, duration: 200})
  let variablePosition = tweened(startPosition, {easing: cubicOut, duration: 400})
  let variableRotation = tweened(startRotation, {easing: cubicOut, duration: 400})
  let cameraPositionBeforeSelection

  let spinInterval = 0
  let isHovering = false

  function selectProduct(){
    if($selectedProductID !== -1)return;
    
    variablePosition.set($selectedProductPosition.map((val, idx) => val + ([0, verticalProductOffset, 0][idx] || 0)))
    variableRotation.set($selectedProductRotation)
    spinInterval = setInterval(() => {
      variableRotation.update(rot => [rot[0], rot[1] + $selectedProductRotationSpeed, rot[2]])
    }, 64);

    //save old camera Position
    cameraPositionBeforeSelection = $cameraControls.getPosition()

    $cameraControls.setLookAt(
      //camera Position when selecting Porduct
      $selectedProductPosition[0] + 10, 
      $selectedProductPosition[1] + 3, 
      $selectedProductPosition[2] - 10, 
      //camera LookAt when selecting Porduct
      $selectedProductPosition[0], 
      $selectedProductPosition[1], 
      $selectedProductPosition[2], 
      true
    )

    //disable movement
    $cameraControls.enabled = false

    $selectedProductID = productData.id
  }

  function deselectProduct(){
    if(!isSelected())return
    variablePosition.set(startPosition)
    variableRotation.set(startRotation)
    clearInterval(spinInterval);

    //move Camera to old Position
    $cameraControls.setLookAt(
      cameraPositionBeforeSelection.x, 
      cameraPositionBeforeSelection.y, 
      cameraPositionBeforeSelection.z,
      $selectedProductPosition[0], 
      $selectedProductPosition[1] + 2, 
      $selectedProductPosition[2], 
      true
    )

    //enable movement
    $cameraControls.enabled = true

    setTimeout(() => {
      $selectedProductID = -1
    }, 50);
  }

  triggerDeselect.subscribe((value) => {
    if (value) {
      deselectProduct();
      triggerDeselect.set(false); 
    }
  });

  function isSelected() {
    return $selectedProductID === productData.id
  }

  let wosh1,wosh2;
</script>

<Audio src={'./static/sounds/wosh1.flac'} bind:this={wosh1} />
<Audio src={'./static/sounds/wosh2.flac'} volume={0.5} bind:this={wosh2} />

{#if $selectedProductID === -1 && isHovering}
  <HTML
    position.x={$variablePosition[0]}
    position.y={$variablePosition[1] + 2.3}
    position.z={$variablePosition[2]}
    rotation={$variableRotation}
    transform
    portal={document.body}
  >
    <h1 style="background-color: white; padding: 0.4rem; border-radius: 1rem;">{productData.name}</h1>
  </HTML>
{/if}

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={$variableScale} position={$variablePosition} rotation={$variableRotation}
  on:pointerover={() => {
    if($selectedProductID < 0){
      variableScale.set(scale + 0.3)
      isHovering = true
      document.body.style.cursor = 'pointer';
    }
  }}
  on:pointerout={() => {
    variableScale.set(scale)
    isHovering = false
    document.body.style.cursor = 'default';
  }}
  on:click={(event) => {
    event.stopPropagation();
    selectProduct()
    wosh1.play();
  }}
  on:pointermissed={(event) => {
    event.stopPropagation();
    deselectProduct()
    if($selectedProductID > 0)wosh2.play();
  }}
>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <T.Group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1_1.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1_2.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1_3.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1_4.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.fbx_1_5.geometry}
      material={gltf.materials.Knit_Cotton_Jersey_FRONT_2800}
    />
  </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>